import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [".next/**", "node_modules/**", "coverage/**", "next-env.d.ts"],
  },
  {
    rules: {
      // Marketing copy uses apostrophes in JSX; escaping hurts readability.
      "react/no-unescaped-entities": "off",
      // Generated by Next.js — triple-slash reference is intentional.
      "@typescript-eslint/triple-slash-reference": "off",
    },
  },
];

export default eslintConfig;
